# Generated by Django 6.0.3 on 2026-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField()),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
    ]
